name: remote_jupyter_env
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.12
  - jupyter
  - notebook
  - jupyterlab
  - ipykernel
  - ipywidgets
  - jupyterlab_widgets
  - widgetsnbextension

  # Core ML
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - plotly
  - openpyxl
  - pyarrow
  - xgboost
  - catboost
  - lightgbm

  # PyTorch + CUDA
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda

  # PyTorch ecosystem
  - pytorch-lightning
  - torchmetrics
  - timm
  - torchinfo
  - captum
  - optuna

  # Monitoring and experiment tracking
  - mlflow
  - wandb
  - tensorboard

  # Development
  - pandas-profiling
  - scikit-optimize
  - seaborn-image
  - ultralytics

  - pip:
      - label-studio-ml
      - torchsummary
      - debugpy
